- name: Ensure depdencies are installed
  become: yes
  apt:
    name: [apt-transport-https, ca-certificates, curl, software-properties-common]
    state: present
  tags: docker


- name: Docker-py is present
  become: yes
  pip:
    name: docker-py
  tags: docker


- name: Add Docker apt key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: true
  tags: docker


- name: Add Docker repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
  tags: docker


- name: Install Docker
  become: yes
  package:
    name: docker-ce
    state: present
  tags: docker


- name: Docker started and enabled at boot
  become: yes
  service:
    name: docker
    state: started
    enabled: yes
  tags: docker


- name: Deploy user is added to the docker group
  become: yes
  user:
    name: ubuntu
    groups: sudo,docker
    append: yes
  register: user_result
  tags: docker


- name: Reset SSH connection to allow user group changes
  meta: reset_connection
  tags: docker